language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
branches:
  only:
  - master
before_install:
 - composer self-update
before_script:
- composer install
script:
- phpunit --debug -c phpunit.xml.dist
after_script:
- php vendor/bin/coveralls
env:
  global:
  - secure: DoPWJWWbEHWXxX/gGf49vE9oszcIbDy/i35AihPvzbpICN6GuWuYVYhUR74X9ApeSkl03LyVccHUMUVQEnTC6KxN2bNqjjjy7SyM11XMZ6r29iaCaHp+M5DmCIrPNdvEIKTewce7QUEpzOhGCQDS9nJ/Jvs8zVythLs6Y6XrMnk=
  - secure: IiTCsLcfQVrMs0EMj5FgVu8eLi+GXbJBI9P40B2UtL9MWmzKXzmNbCAroM1nWydQUNU2iCLOnB3nNn90Du6A103iPp7RJ1aevkbDycCqrcRh6THVCfJne56Y4BcWt/qF5mHIYQceiuDKq2TqbENBRK4cLJIVqNlEl0rl/4HrP4k=
